version: "3.8"
services:
  dynamics-mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: tiger
    volumes:
      - mysqldata:/var/lib/mysql

  app:
    image: vvijayakumarm/dynamics-att:1.0
    depends_on:
      - dynamics-mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dynamics-mysql:3306/dynamics101
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: tiger

volumes:
  mysqldata:
